sudo: required #for super user privileges
language: generic

services:
  - docker

before_install:
  - docker build -t safranci89/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true safranci89/docker-react npm run test

