version: '3'
services:
  client-app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - /usr/app/node_modules
      - ./src:/usr/app/src
  test-suite:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - /usr/app/node_modules
      - ./src:/usr/app/src
    command: ["npm", "run", "test"]
